resolver: lts-12.16
packages:
- cmdline
- dataiter
extra-deps:
- ../mxnet-hs/base
- ../mxnet-hs/operators
- ../mxnet-nn
- ../tuple-ops
- ../type-combinators
- c2hs-extra-0.1.0.1
- streaming-utils-0.1.4.7
- graphviz-2999.20.0.2
- fgl-5.5.4.0
extra-include-dirs:
- /home/jiasen/dschungel/incubator-mxnet/include
- /home/jiasen/dschungel/incubator-mxnet/nnvm/include/
extra-lib-dirs:
- /home/jiasen/dschungel/incubator-mxnet/lib
