resolver: lts-10.7
packages:
- .
extra-deps:
- git: https://github.com/sighingnow/mxnet-haskell.git
  commit: 3d6cfb301f0e4f1c21c2596de27446b51d8162ae 
  subdirs:
  - mxnet
- c2hs-extra-0.1.0.1
- tuple-ops-0.0.0.1 
extra-include-dirs:
- /home/jwu/incubator-mxnet/include
- /home/jwu/incubator-mxnet/nnvm/include/
extra-lib-dirs:
- /home/jwu/incubator-mxnet/lib